### ISSUE TITLE
Add DAG-CBOR example

### ISSUE THREAD

**Issue by lidel** [ipfs/ipld-explorer-components#355]
Add [ipfs-geoip](https://www.npmjs.com/package/ipfs-geoip) as example of DAG-CBOR DAG.

it is a tiny library, I suggest making it a dependency, so we always point at the latest `GEOIP_ROOT`:
https://github.com/ipfs-shipyard/ipfs-geoip/blob/466cd9d6454098c0fcf998b2217225099a654695/src/lookup.js#L9

**Comment by SgtPooki** [comment]
this will be fixed when i resolve #359

**Comment by lidel** [comment]
@rvagg @ribasushi  @vmx  @RangerMauve do you have any DAG-CBOR CIDs worth surfacing here? 
@hacdias is working on https://github.com/ipfs/boxo/issues/307 and having more real world examples benefits both this PR and  the gateway work.

**Comment by RangerMauve** [comment]
We've got the Prolly Tree fixtures here which might be relevant: https://github.com/kenlabs/go-ipld-prolly-trees/tree/dev/pkg/tree/fixtures/10000RandPairs
