### ISSUE TITLE
fix: remove dependency on Buffer global

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/ipld-explorer-components#453]
https://github.com/ipfs/ipld-explorer-components/blob/5c9718335e81cb3a06f7540a0be5135fe6355ad5/src/lib/normalise-dag-node.ts#L127

I don't think this would ever return true. see https://nodejs.org/api/buffer.html#static-method-bufferisbufferobj

**Comment by 07Vaishnavi-Singh** [comment]
Hey can I solve this issue as a contribution in my PLDG cohort 1 participation 
Would be great if you can assign it to me :)

**Comment by 07Vaishnavi-Singh** [comment]
Let me know if I got the problem right :) 
If I got that wrong can you please tell a bit about the problem will fix it accordingly 
Thanks in Advance

**Comment by SgtPooki** [comment]
@07Vaishnavi-Singh I reviewed the PR. I didn't see any changes, only a submodule added, which we don't want
